app/src/main/resources/application.properties, app/src/main/resources/application.yml, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/ElementInstanceRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/IncidentRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/JobRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/WorkflowInstanceRepository.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/query/IncidentQueryResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/query/JobQueryResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/query/WorkflowInstanceQueryResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/WorkflowInstanceResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/WorkflowResolver.kt, graphql-api/src/main/resources/graphql/Incident.graphqls, graphql-api/src/main/resources/graphql/Job.graphqls, graphql-api/src/main/resources/graphql/Workflow.graphqls, graphql-api/src/main/resources/graphql/WorkflowInstance.graphqls
* filter workflow instances by state
* filter jobs by state and job type
* filter incidents by state
* filter element instances by state
closes #8 
closes #9 
closes #10
=> feat(graphql): introduce filters

hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastConfig.kt, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastConfigRepository.kt, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastImporter.kt, pom.xml
* store the sequence number of the ringbuffer in the database
* continue from the last read sequence on startup
=> chore(hazelcast): manage ringbuffer sequence number

hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastImporter.kt
=> fix(hazelcast): don't import records with negative keys

data/src/main/kotlin/io/zeebe/zeeqs/data/repository/IncidentRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/JobRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/WorkflowInstanceRepository.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/query/IncidentQueryResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/query/JobQueryResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/query/MessageQueryResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/query/WorkflowInstanceQueryResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/query/WorkflowQueryResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/IncidentList.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/IncidentListResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/JobList.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/JobListResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/MessageList.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/MessageListResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/WorkflowInstanceList.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/WorkflowInstanceListResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/WorkflowList.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/WorkflowListResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/WorkflowResolver.kt, graphql-api/src/main/resources/graphql/Incident.graphqls, graphql-api/src/main/resources/graphql/Job.graphqls, graphql-api/src/main/resources/graphql/Message.graphqls, graphql-api/src/main/resources/graphql/Workflow.graphqls, graphql-api/src/main/resources/graphql/WorkflowInstance.graphqls, graphql-api/src/test/kotlin/io/zeebe/zeeqs/ZeebeGraphqlTest.kt
* unify pagination for the query
* add pagination for workflow to workflow instances connection
closes #7
=> feat(graphql): unify pagination for queries

README.md, app/src/main/resources/application.yml, docker/docker-compose.yml
* adjust the Hazelcast connection properties
=> Update to new Hazelcast configuration

data/src/main/kotlin/io/zeebe/zeeqs/data/entity/ElementInstance.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/ElementInstanceStateTransition.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/Incident.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/Job.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/Message.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/MessageSubscription.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/Timer.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/Variable.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/VariableUpdate.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/WorkflowInstance.kt
Change all enum fields on entities to be @Enumerated(EnumType.STRING) 
add @Lob to Incident.errorMessage
=> jpa improvements

README.md, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/connection/WorkflowResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/query/IncidentQueryResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/query/JobQueryResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/query/MessageQueryResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/query/WorkflowInstanceQueryResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/query/WorkflowQueryResolver.kt, graphql-api/src/main/resources/graphql/Incident.graphqls, graphql-api/src/main/resources/graphql/Job.graphqls, graphql-api/src/main/resources/graphql/Message.graphqls, graphql-api/src/main/resources/graphql/Workflow.graphqls, graphql-api/src/main/resources/graphql/WorkflowInstance.graphqls
=> Replace the pagination parameter "limit" with "perPage"

data/src/main/kotlin/io/zeebe/zeeqs/data/repository/IncidentRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/VariableRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/VariableUpdateRepository.kt
* add missing @Transactional for loading large objects (LOB)
closes #92
=> Avoid database exception when loading large objects

data/src/main/kotlin/io/zeebe/zeeqs/data/entity/Error.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/ErrorRepository.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/connection/ErrorConnection.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/connection/ErrorConnectionResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/query/ErrorQueryResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/ErrorResolver.kt, graphql-api/src/main/resources/graphql/Error.graphqls, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastImporter.kt
* import error records from Hazelcast and expose them as GraphQL query
closes #45
=> Import error records and expose them via GraphQL

.github/workflows/build.yml, .github/workflows/deploy.yml, hazelcast-importer/src/test/kotlin/io/zeebe/zeeqs/HazelcastImporterTest.kt, pom.xml
* basic GitHub workflow to build and deploy Maven artifacts
=> chore(ci): build and deploy artifacts using GitHub actions

.github/workflows/build.yml, .github/workflows/deploy.yml, app/pom.xml
:warning: test on how to publish Docker images to GitHub packages
=> chore(ci): publish docker image to GitHub

.github/workflows/deploy.yml, app/pom.xml
Build the Docker image in `deploy` phase instead of using an additional build step.
=> chore(project): build Docker image on deploy step

app/pom.xml, data/pom.xml, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/BpmnElementType.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/service/WorkflowService.kt, data/src/test/kotlin/io/zeebe/zeeqs/WorkflowServiceTest.kt, graphql-api/pom.xml, hazelcast-importer/pom.xml, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastImporter.kt, hazelcast-importer/src/test/kotlin/io/zeebe/zeeqs/HazelcastImporterTest.kt, pom.xml
* dump zeebe version from 0.26.3 to 1.0.0
* dump hazelcast exporter version from 0.10.0 to 1.0.0
=> Update to Zeebe 1.0.0

app/pom.xml, data/pom.xml, data/src/test/kotlin/io/zeebe/zeeqs/ProcessServiceH2Test.kt, data/src/test/kotlin/io/zeebe/zeeqs/ProcessServicePostgresTest.kt, data/src/test/kotlin/io/zeebe/zeeqs/ProcessServiceTest.kt, data/src/test/resources/application-postgres-docker.properties, pom.xml
I've added the Postgres driver as a dependency so it could be available in the container app classpath.
Closes #129
=> Add the postgres driver

README.md
- Add example in README.md
- Correct example value in README.md
Happy merging!
=> Add example in README.md

graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/MessageCorrelationResolver.kt, graphql-api/src/main/resources/graphql/MessageSubscription.graphqls
* add edge to get the process instance of a message correlation
=> feat: get process instance of message correlation

data/src/main/kotlin/io/zeebe/zeeqs/data/repository/ElementInstanceStateTransitionRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/MessageCorrelationRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/MessageRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/VariableUpdateRepository.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/query/MessageQueryResolver.kt, graphql-api/src/main/resources/graphql/Message.graphqls, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastImporter.kt
Extend the message query by a state filter.
=> feat: query messages by state

data/src/main/kotlin/io/zeebe/zeeqs/data/entity/MessageSubscriptionState.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/MessageSubscriptionResolver.kt, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastImporter.kt
* import message subscriptions from process subscription records to retrieve the element id
* resolve the process definition key from the process instance because the subscription doesn't have a reference to it
=> fix: import message subscriptions with element id

graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/ProcessResolver.kt, graphql-api/src/main/resources/graphql/Process.graphqls
* find BPMN element of process by its it
=> feat: find process element by id

data/src/main/kotlin/io/zeebe/zeeqs/data/service/BpmnElementInfo.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/service/BpmnElementMetadata.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/service/MessageSubscriptionDefinition.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/service/ProcessService.kt, data/src/test/kotlin/io/zeebe/zeeqs/ProcessServiceTest.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/BpmnElementResolver.kt, graphql-api/src/main/resources/graphql/Element.graphqls
* expose the following properties of a BPMN element:
* message subscription definition
* called process id
* error code
* timer definition
* condition expression
* job type
closes #11
=> Expose BPMN element metadata

data/src/main/kotlin/io/zeebe/zeeqs/data/repository/ErrorRepository.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/ProcessInstanceResolver.kt, graphql-api/src/main/resources/graphql/ProcessInstance.graphqls
* extend GraphQL API to get an error of a process instance
=> feat: get error of process instance

data/src/main/kotlin/io/zeebe/zeeqs/data/entity/BpmnElementType.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/service/ProcessService.kt, graphql-api/src/main/resources/graphql/Element.graphqls, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastImporter.kt
Add a new BPMN element type for inclusive gateways. Since Zeebe 8.1, inclusive gateways are supported.
=> feat: Add new BPMN element type for inclusive gateways

pom.xml
- fix the build by updating the Maven plugins
- switch to the Camunda community Maven parent
=> build: Update maven plugins

data/src/main/kotlin/io/zeebe/zeeqs/data/entity/DecisionEvaluation.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/DecisionEvaluationInput.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/DecisionEvaluationOutput.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/DecisionEvaluationState.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/EvaluatedDecision.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/DecisionEvaluationInputRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/DecisionEvaluationOutputRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/DecisionEvaluationRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/DecisionRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/EvaluatedDecisionRepository.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/connection/DecisionEvaluationConnection.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/connection/DecisionEvaluationConnectionResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/DecisionEvaluationResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/DecisionResolver.kt, graphql-api/src/main/resources/graphql/Decision.graphqls, graphql-api/src/main/resources/graphql/DecisionEvaluation.graphqls, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastDecisionEvaluationImporter.kt, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastDecisionImporter.kt, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastImporter.kt, hazelcast-importer/src/test/kotlin/io/zeebe/zeeqs/HazelcastImporterDecisionTest.kt
Import decision evaluations from Hazelcast and expose them via the GraphQL API.
---
Query:
```graphql
{
decision(key: 2251799813685251) {
decisionId
decisionName
evaluations {
totalCount
nodes {
key
decision {
decisionId
}
decisionOutput
state
evaluatedDecisions {
decision {
decisionId
}
decisionOutput
inputs {
inputId
inputName
value
}
matchedRules {
ruleId
ruleIndex
outputs {
outputId
outputName
value
}
}
}
processInstance {
key
process {
bpmnProcessId
}
}
elementInstance {
element {
elementName
}
}
}
}
}
}
```
Response:
```json
{
"data": {
"decision": {
"decisionId": "department_line_manager",
"decisionName": "Department line manager",
"evaluations": {
"totalCount": 1,
"nodes": [
{
"key": "2251799813685268",
"decision": {
"decisionId": "department_line_manager"
},
"decisionOutput": …
```
=> feat: Add GraphQL API for decision evaluation
