graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/ElementInstanceResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/ElementInstanceStateTransitionResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/IncidentResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/JobResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/MessageCorrelationResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/MessageResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/MessageSubscriptionResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/ResolverExtension.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/TimerResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/VariableResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/VariableUpdateResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/WorkflowInstanceResolver.kt, graphql-api/src/main/resources/graphql/ElementInstance.graphqls, graphql-api/src/main/resources/graphql/Incident.graphqls, graphql-api/src/main/resources/graphql/Job.graphqls, graphql-api/src/main/resources/graphql/Message.graphqls, graphql-api/src/main/resources/graphql/MessageSubscription.graphqls, graphql-api/src/main/resources/graphql/Timer.graphqls, graphql-api/src/main/resources/graphql/Variable.graphqls, graphql-api/src/main/resources/graphql/WorkflowInstance.graphqls, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastImporter.kt
* instead of returning a timestamp as long, using the ISO8601 date-time string format
* the zone-id can be passed via optional argument
=> feat(graphql): return ISO8601 string instead of timestamp

data/src/main/kotlin/io/zeebe/zeeqs/data/entity/Job.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/Timer.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/JobResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/TimerResolver.kt, graphql-api/src/main/resources/graphql/Job.graphqls, graphql-api/src/main/resources/graphql/Timer.graphqls, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastImporter.kt
* replace the timer's timestamp with a start and an end time
* add a start and end time to the job
* expose start and end time via GraphQL
closes #19
=> feat(data): add start and end time for timers and jobs

data/src/main/kotlin/io/zeebe/zeeqs/data/entity/Workflow.kt, data/src/test/kotlin/io/zeebe/zeeqs/WorkflowServiceTest.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/WorkflowResolver.kt, graphql-api/src/main/resources/graphql/Workflow.graphqls, graphql-api/src/test/kotlin/io/zeebe/zeeqs/ZeebeGraphqlTest.kt, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastImporter.kt, hazelcast-importer/src/test/kotlin/io/zeebe/zeeqs/HazelcastImporterTest.kt
* unify deployment time to return a string instead of long timestamp
* rename timestamp to deployTime
=> fix(graphql): return deployment time as ISO-8601 string

.github/workflows/deploy.yml, app/pom.xml
Simplify the build/deploy process by using the project version as the docker image tag. 
Avoid tagging the docker image as `latest` because it seems not recommended.
=> build(docker): use the project version as the docker image tag

data/src/main/kotlin/io/zeebe/zeeqs/data/entity/ElementInstanceStateTransition.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/MessageCorrelation.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/VariableUpdate.kt, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastImporter.kt
* change primary key of state transition, message correlation, and variable update from position to a compound key of partition id and position
* positions are not unique if the broker has more than one partition
closes #162
=> fix: avoid duplicated keys on multi-partition

data/src/main/kotlin/io/zeebe/zeeqs/data/entity/Process.kt
* Postgres fails to import processes if the checksum contains a non-UTF8 character
* change the database type of the checksum to LOB to store it as binary data
close #257
=> fix: store the checksum in the database as LOB

.github/workflows/deploy.yml, Jenkinsfile, app/pom.xml, pom.xml
There is a default profile (`jib-local`) for local build and the `jib-multiplatform` profile to build the multiplatform images.
Closes #281
=> feat: multiplatform docker image via JIB

data/src/main/kotlin/io/zeebe/zeeqs/data/service/BpmnElementMetadata.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/service/ProcessService.kt, data/src/test/kotlin/io/zeebe/zeeqs/ProcessServiceTest.kt, graphql-api/src/main/resources/graphql/Element.graphqls
I can access the following static properties of a user task. 
- the assignee
- the candidate groups
closes #283
=> feat: add metadata of user task

data/src/main/kotlin/io/zeebe/zeeqs/data/service/BpmnElementMetadata.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/service/ProcessService.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/service/UserTaskAssignmentDefinition.kt, data/src/test/kotlin/io/zeebe/zeeqs/ProcessServiceTest.kt, graphql-api/src/main/resources/graphql/Element.graphqls
Group the user task metadata into its own type. Both properties `assignee` and `canidateGroups` belongs to user tasks. 
Zeebe 8.2 will introduce a new property `candidateUsers`.
=> refactor: Group the user task metadata into a type

data/src/main/kotlin/io/zeebe/zeeqs/data/entity/Timer.kt, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastImporter.kt
Set the process instance key when a timer is triggered. Since Zeebe `8.1`, the timer record with intent `triggered` contains the key of the process instance. Previously, the timer record doesn't contain key if it was for a timer start event.
close #246
=> feat: set the process instance key when a timer is triggered

data/src/main/kotlin/io/zeebe/zeeqs/data/repository/VariableRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/service/VariableService.kt, data/src/test/kotlin/io/zeebe/zeeqs/ProcessServiceTest.kt, data/src/test/kotlin/io/zeebe/zeeqs/TestConfiguration.kt, data/src/test/kotlin/io/zeebe/zeeqs/VariableServiceTest.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/ElementInstanceResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/ProcessInstanceResolver.kt, graphql-api/src/main/resources/graphql/ElementInstance.graphqls, graphql-api/src/main/resources/graphql/ProcessInstance.graphqls, graphql-api/src/test/kotlin/io/zeebe/zeeqs/ZeebeGraphqlVariableTest.kt
* add a new connection from `element instance` to `variable`
* get all local variables by default
* if `localOnly` is `false`, get all local variables and variables from upper scopes (i.e. all visible variables)
* if `shadowing` is `false`, get all variables, including variables with the same name
* if `shadowing` is `true`, get all variables but exclude variables with the same name from upper scopes (i.e. variable shadowing)
* add a new option for `process instance` to return only the global variables
=> Get variables of process instance

data/src/main/kotlin/io/zeebe/zeeqs/data/entity/UserTask.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/service/BpmnElementMetadata.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/service/ProcessService.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/service/UserTaskForm.kt, data/src/test/kotlin/io/zeebe/zeeqs/ProcessServiceTest.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/ProcessResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/UserTaskResolver.kt, graphql-api/src/main/resources/graphql/Element.graphqls, graphql-api/src/main/resources/graphql/Process.graphqls, graphql-api/src/test/kotlin/io/zeebe/zeeqs/ZeebeGraphqlProcessTest.kt, graphql-api/src/test/kotlin/io/zeebe/zeeqs/ZeebeGraphqlUserTaskTest.kt, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastImporter.kt, hazelcast-importer/src/test/kotlin/io/zeebe/zeeqs/HazelcastImporterJobTest.kt
- add the property `userTaskForm` to the BPMN element metadata 
- the form has a `formKey`
- the form can have a `resource` (i.e. the form JSON definition)
- add an option to filter `elements` of a process by their BPMN type
=> Get user tasks forms as metadata

pom.xml
Dump `zeebe-hazelcast-exporter` from `1.2.1` to [1.3.0](https://github.com/camunda-community-hub/zeebe-hazelcast-exporter/releases/tag/1.3.0).
=> deps: dump zeebe-hazelcast-exporter from 1.2.1 to 1.3.0

data/src/main/kotlin/io/zeebe/zeeqs/data/repository/DecisionEvaluationRepository.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/ElementInstanceResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/ProcessInstanceResolver.kt, graphql-api/src/main/resources/graphql/ElementInstance.graphqls, graphql-api/src/main/resources/graphql/ProcessInstance.graphqls
Add a connection in the GraphQL API from process instance and element instance to decision evaluations.
Related to https://github.com/camunda-community-hub/zeeqs/issues/286
=> feat: Fetch decision evaluations by process instance

graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/DecisionEvaluationResolver.kt, graphql-api/src/main/resources/graphql/DecisionEvaluation.graphqls
Add a field in the GraphQL API for decision evaluations to retrieve the time of the evaluation.
Related to https://github.com/camunda-community-hub/zeeqs/issues/286
=> feat: Get the evaluation time of the decision

data/src/main/kotlin/io/zeebe/zeeqs/data/reactive/DataUpdatesPublisher.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/reactive/DataUpdatesSubscription.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/subscription/DecisionEvaluationSubscriptionMapping.kt, graphql-api/src/main/resources/graphql/DecisionEvaluation.graphqls, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastDecisionImporter.kt
Add a new subscription to the GraphQL API for decision evaluations. 
---
Subscribe to all decision evaluations:
```graphql
subscription {
decisionEvaluationUpdates {
key
decision {
key
decisionId
}
decisionOutput
state
}
}
```
Response message:
```json
{
"data": {
"decisionEvaluationUpdates": {
"key": "2251799813685390",
"decision": {
"key": "2251799813685277",
"decisionId": "decision_a"
},
"decisionOutput": "\"A+\"",
"state": "EVALUATED"
}
}
}
```
---
Related to https://github.com/camunda-community-hub/zeeqs/issues/286
=> feat: Subscribe to decision evaluation updates

data/src/main/kotlin/io/zeebe/zeeqs/data/repository/DecisionEvaluationRepository.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/query/DecisionEvaluationQueryResolver.kt, graphql-api/src/main/resources/graphql/DecisionEvaluation.graphqls
Add a new query to the GraphQL API for decision evaluations. 
---
Query all decision evaluations:
```graphql
{
decisionEvaluations {
totalCount
nodes {
key
decision {
decisionId
}
state
decisionOutput
evaluationTime
}
}
}
```
Response:
```json
{
"data": {
"decisionEvaluations": {
"totalCount": 12,
"nodes": [
{
"key": "2251799813685268",
"decision": {
"decisionId": "department_line_manager"
},
"state": "EVALUATED",
"decisionOutput": "\"Ringo\"",
"evaluationTime": "2023-03-02T04:37:48.004Z"
}
]
}
}
}
```
---
Related to https://github.com/camunda-community-hub/zeeqs/issues/286
=> feat: Query for decision evaluations

data/src/main/kotlin/io/zeebe/zeeqs/data/repository/DecisionEvaluationRepository.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/DecisionResolver.kt, graphql-api/src/main/resources/graphql/Decision.graphqls
Add support for pagination on fetching evaluations for a decision. 
Currently, the parameters are missing and the connection returns all evaluations.
=> fix: Add pagination on fetching evaluations for a decision

data/src/main/kotlin/io/zeebe/zeeqs/data/repository/DecisionRepository.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/DecisionEvaluationResolver.kt, pom.xml
Since ZeeQS is based on Java 17, we can switch from `kotlin-stdlib` to `kotlin-stdlib-jdk8`. The `jdk8` version is common for new projects.
=> deps: switch from kotlin-stdlib to kotlin-stdlib-jdk8

data/src/main/kotlin/io/zeebe/zeeqs/data/repository/DecisionEvaluationRepository.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/ProcessInstanceResolver.kt, graphql-api/src/main/resources/graphql/ProcessInstance.graphqls
Add the missing pagination to the GraphQL API when fetching the decision evaluations of a process instance.
The change in the API is backward-compatible because it uses default values.
=> fix: Add missing pagination for fetching decision evaluations

data/src/main/kotlin/io/zeebe/zeeqs/data/repository/TimerRepository.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/ProcessInstanceResolver.kt
A timer of a process instance must have an element instance key. It is not enough to filter by a process instance key because a timer of a process start event will have also a process instance key after it is triggered.
related to https://github.com/camunda-community-hub/zeebe-play/issues/66
=> fix: Filter timers of process instance

pom.xml
Dump `zeebe-hazelcast-exporter` from `1.3.0` to [1.4.0](https://github.com/camunda-community-hub/zeebe-hazelcast-exporter/releases/tag/1.4.0).
=> deps: dump zeebe-hazelcast-exporter from 1.3.0 to 1.4.0

data/src/main/kotlin/io/zeebe/zeeqs/data/entity/Signal.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/SignalSubscription.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/SignalSubscriptionState.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/entity/SignalVariable.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/SignalRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/SignalSubscriptionRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/repository/SignalVariableRepository.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/service/BpmnElementMetadata.kt, data/src/main/kotlin/io/zeebe/zeeqs/data/service/ProcessService.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/connection/SignalConnection.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/connection/SignalConnectionResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/query/SignalQueryResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/ProcessResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/SignalResolver.kt, graphql-api/src/main/kotlin/io/zeebe/zeeqs/graphql/resolvers/type/SignalSubscriptionResolver.kt, graphql-api/src/main/resources/graphql/Element.graphqls, graphql-api/src/main/resources/graphql/Process.graphqls, graphql-api/src/main/resources/graphql/Signal.graphqls, graphql-api/src/main/resources/graphql/SignalSubscription.graphqls, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastImporter.kt, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/HazelcastSignalImporter.kt, hazelcast-importer/src/main/kotlin/io/zeebe/zeeqs/importer/hazelcast/ProtobufTransformer.kt
Expose signals and signal subscriptions via GraphQL API.
---
Fetch signal subscriptions of a process:
```graphql
processes {
nodes {
bpmnProcessId
signalSubscriptions {
key
signalName
state
timestamp
process {
bpmnProcessId
}
element {
elementId
elementName
bpmnElementType
}
}
}
}
```
<details>
<summary>Response</summary>
<pre>
```json
{
"processes": {
"nodes": [
{
"bpmnProcessId": "signal-process",
"signalSubscriptions": [
{
"key": "2251799813685251",
"signalName": "signal-start",
"state": "DELETED",
"timestamp": "2023-04-06T04:43:43.394Z",
"process": {
"bpmnProcessId": "signal-process"
},
"element": {
"elementId": "StartEvent_1",
"elementName": null,
"bpmnElementType": "START_EVENT"
}
}
]
},
{
"bpmnProcessId": "signal-process",
"signalSubscriptions": [
{
"key": "2251799813685254", …
```
=> feat: Expose signals and subscriptions in the GraphQL API
